# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivemoney',
            options={'default_permissions': [], 'managed': False, 'permissions': (('view_receivemoney', '结算-查看'),), 'verbose_name': '收款'},
        ),
    ]
