# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySign',
            fields=[
                ('signId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('linkPhone', models.CharField(max_length=20)),
                ('carNo', models.CharField(blank=True, max_length=20, null=True)),
                ('signNum', models.IntegerField()),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
            ],
            options={
                'verbose_name': '活动报名',
                'permissions': (('view_activitysign', '活动-报名-查看'),),
                'db_table': 'activitySign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RidersActivity',
            fields=[
                ('raId', models.AutoField(primary_key=True, serialize=False)),
                ('acTitle', models.CharField(max_length=20)),
                ('acBody', models.TextField()),
                ('acTime', models.DateTimeField()),
                ('acAddress', models.CharField(max_length=30)),
                ('totalNum', models.IntegerField(blank=True, null=True)),
                ('signflag', models.BooleanField()),
                ('signNum', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('createdUser', models.CharField(max_length=20)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('updatedUser', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '活动',
                'permissions': (('view_ridersactivity', '活动-查看'),),
                'db_table': 'ridersActivity',
                'managed': False,
            },
        ),
    ]
