# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adposition',
            fields=[
                ('posiId', models.AutoField(primary_key=True, serialize=False)),
                ('posiName', models.CharField(max_length=20)),
                ('posiNo', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('createdUser', models.CharField(max_length=20)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('updatedUser', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '广告位',
                'permissions': (('view_adposition', '广告-广告位-查看'),),
                'db_table': 'adPosition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('adId', models.AutoField(primary_key=True, serialize=False)),
                ('sortNo', models.SmallIntegerField(blank=True, null=True)),
                ('adType', models.SmallIntegerField()),
                ('title', models.CharField(max_length=80)),
                ('adContents', models.TextField(blank=True, null=True)),
                ('linkUrl', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('createdUser', models.CharField(max_length=20)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('updatedUser', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '广告',
                'permissions': (('view_advertisement', '广告-查看'),),
                'db_table': 'advertisement',
                'managed': False,
            },
        ),
    ]
