# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('infoType', models.SmallIntegerField()),
                ('carNoFix', models.CharField(max_length=1)),
                ('carNo', models.CharField(max_length=20)),
                ('vin', models.CharField(blank=True, max_length=30, null=True)),
                ('engineNo', models.CharField(blank=True, max_length=50, null=True)),
                ('ownerNo', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
                ('configType', models.CharField(blank=True, max_length=50, null=True)),
                ('brandType', models.CharField(blank=True, max_length=30, null=True)),
                ('annualSurveyDate', models.DateField(blank=True, null=True)),
                ('insuranceDate', models.DateField(blank=True, null=True)),
                ('registerDate', models.DateField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('drivingPermitUrl', models.CharField(blank=True, max_length=80, null=True)),
                ('identityCardUrl', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '车辆',
                'permissions': (('view_carinfo', '车主-车辆-查看'),),
                'db_table': 'carInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendRelate',
            fields=[
                ('relateId', models.AutoField(primary_key=True, serialize=False)),
                ('firstUserId', models.IntegerField(blank=True, null=True)),
                ('secondUserId', models.IntegerField(blank=True, null=True)),
                ('threeUserId', models.IntegerField(blank=True, null=True)),
                ('fourUserId', models.IntegerField(blank=True, null=True)),
                ('fiveUserId', models.IntegerField(blank=True, null=True)),
                ('recommendTotal', models.IntegerField(blank=True, null=True)),
                ('communityTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('awardTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'recommendRelate',
                'verbose_name': '用户推荐',
            },
        ),
        migrations.CreateModel(
            name='ThirdAccount',
            fields=[
                ('tacId', models.AutoField(primary_key=True, serialize=False)),
                ('accType', models.SmallIntegerField(blank=True, null=True)),
                ('accountNo', models.CharField(max_length=30)),
                ('bankName', models.CharField(max_length=20)),
                ('cardType', models.CharField(max_length=20)),
                ('realName', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'thirdAccount',
                'verbose_name': '第三方账号',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('registerTime', models.DateTimeField()),
                ('failureNumber', models.SmallIntegerField()),
                ('lastLoginTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': '用户',
                'permissions': (('view_user', '车主-查看'),),
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('infoId', models.AutoField(primary_key=True, serialize=False)),
                ('payPwd', models.CharField(blank=True, db_column='payPwd', max_length=12, null=True)),
                ('awardBalance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rechargeBalance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('referralCode', models.CharField(blank=True, max_length=6, null=True)),
                ('userImg', models.CharField(blank=True, max_length=80, null=True)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.NullBooleanField()),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('constellation', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('hobby', models.CharField(blank=True, max_length=50, null=True)),
                ('defaultShopId', models.IntegerField(blank=True, null=True)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'userInfo',
                'verbose_name': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='UserRecommendStatistical',
            fields=[
                ('ursId', models.IntegerField(primary_key=True, serialize=False)),
                ('award', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('community', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'userRecommendStatistical',
                'verbose_name': '用户推荐统计',
            },
        ),
    ]
