# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinfo',
            options={'default_permissions': [], 'managed': False, 'permissions': (('view_carinfo', '车主-车辆-查看'),), 'verbose_name': '车辆'},
        ),
        migrations.AlterModelOptions(
            name='recommendrelate',
            options={'default_permissions': [], 'managed': False, 'verbose_name': '用户推荐'},
        ),
        migrations.AlterModelOptions(
            name='thirdaccount',
            options={'default_permissions': [], 'managed': False, 'verbose_name': '第三方账号'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'default_permissions': [], 'managed': False, 'verbose_name': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='userrecommendstatistical',
            options={'default_permissions': [], 'managed': False, 'verbose_name': '用户推荐统计'},
        ),
    ]
