# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountlog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('accountTime', models.DateTimeField()),
                ('accountType', models.SmallIntegerField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=50)),
                ('rechargeBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currentBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': '账单',
                'permissions': (('view_accountlog', '账务-账单-查看'),),
                'db_table': 'accountLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AwardRecord',
            fields=[
                ('arId', models.AutoField(primary_key=True, serialize=False)),
                ('firstAward', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('secondAward', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('threeAward', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fourAward', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fiveAward', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('communityAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('createdTime', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'awardRecord',
                'verbose_name': '充值推荐奖励',
            },
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('piId', models.AutoField(primary_key=True, serialize=False)),
                ('rechargeAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('awardAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('createdUser', models.CharField(max_length=20)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('updatedUser', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '充值产品',
                'permissions': (('view_payinfo', '账务-充值产品-查看'),),
                'db_table': 'payInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('poId', models.AutoField(primary_key=True, serialize=False)),
                ('payOrderNo', models.CharField(max_length=20)),
                ('payAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('awardAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('channel', models.CharField(max_length=20)),
                ('channelAccount', models.CharField(max_length=20)),
                ('channelNo', models.CharField(blank=True, max_length=30, null=True)),
                ('payTime', models.DateTimeField(blank=True, null=True)),
                ('orderStatus', models.SmallIntegerField()),
                ('productName', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
            ],
            options={
                'verbose_name': '充值',
                'permissions': (('view_payorder', '账务-充值-查看'),),
                'db_table': 'payOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawOrder',
            fields=[
                ('wrId', models.AutoField(primary_key=True, serialize=False)),
                ('wrMoney', models.DecimalField(decimal_places=2, max_digits=20)),
                ('procedureRates', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wrTime', models.DateTimeField(blank=True, null=True)),
                ('accType', models.SmallIntegerField(blank=True, null=True)),
                ('accountNo', models.CharField(max_length=30)),
                ('bankName', models.CharField(max_length=20)),
                ('cardType', models.CharField(max_length=20)),
                ('cardholder', models.CharField(max_length=20)),
                ('orderStatus', models.SmallIntegerField()),
                ('channelNo', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': '提现',
                'permissions': (('view_withdraworder', '账务-提现-查看'), ('audit_withdraworder', '账务-提现-审核')),
                'db_table': 'withdrawOrder',
                'managed': False,
            },
        ),
    ]
