# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170628_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraworder',
            options={'default_permissions': [], 'managed': False, 'permissions': (('view_withdraworder', '账务-提现-查看'), ('audit_withdraworder', '账务-提现-审核')), 'verbose_name': '提现'},
        ),
    ]
