# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shopId', models.AutoField(primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=30)),
                ('linkman', models.CharField(blank=True, max_length=20, null=True)),
                ('provinceId', models.IntegerField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=20, null=True)),
                ('cityId', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('districtId', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('sosLinkman', models.CharField(blank=True, max_length=20, null=True)),
                ('sosPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('createdUser', models.CharField(max_length=20)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('updatedUser', models.CharField(blank=True, max_length=20, null=True)),
                ('fiveSysId', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '门店',
                'permissions': (('view_shop', '门店-查看'),),
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopImg',
            fields=[
                ('imgId', models.AutoField(db_column='imgId', primary_key=True, serialize=False)),
                ('imgUrl', models.CharField(max_length=80)),
                ('imgDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('createdUser', models.CharField(max_length=20)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('updatedUser', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '门店图片',
                'db_table': 'shopImg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopManager',
            fields=[
                ('mgrId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('registerTime', models.DateTimeField()),
            ],
            options={
                'verbose_name': '门店管理员',
                'permissions': (('view_shopmanager', '门店-门店管理员-查看'),),
                'db_table': 'shopManager',
                'managed': False,
            },
        ),
    ]
