# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopimg',
            options={'default_permissions': [], 'managed': False, 'verbose_name': '门店图片'},
        ),
    ]
