# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('headlineId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('imgUrl', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('createdUser', models.CharField(max_length=20)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('updatedUser', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '头条',
                'permissions': (('view_headline', '内容-头条-查看'),),
                'db_table': 'headline',
                'managed': False,
            },
        ),
    ]
