# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 15:35
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRecord',
            fields=[
                ('srId', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=512)),
                ('platformId', models.SmallIntegerField()),
                ('success', models.NullBooleanField()),
                ('sendTime', models.DateTimeField()),
            ],
            options={
                'verbose_name': '短信',
                'permissions': (('view_smsrecord', '系统-短信-查看'),),
                'db_table': 'smsRecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('configId', models.AutoField(primary_key=True, serialize=False)),
                ('configKey', models.CharField(max_length=20)),
                ('configValue', models.CharField(max_length=20)),
                ('configDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('createdTime', models.DateTimeField()),
                ('createdUser', models.CharField(max_length=20)),
                ('updatedTime', models.DateTimeField(blank=True, null=True)),
                ('updatedUser', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'permissions': (('view_sysconfig', '系统-系统配置-查看'),),
                'db_table': 'sysConfig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('realname', models.CharField(blank=True, max_length=20, null=True, verbose_name='真实姓名')),
                ('gender', models.NullBooleanField(max_length=40, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '管理用户',
                'permissions': (('view_user', '系统-用户-查看'), ('change_userperm', '系统-用户-授权')),
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
